// <auto-generated />
namespace SalaryCalc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CalculatedSalaryByUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CalculatedSalaryByUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201908072102398_CalculatedSalaryByUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
